[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet publish/AnastasiiaPortfolio.dll"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:${PORT}" 