[build]
builder = "nixpacks"
buildCommand = "dotnet publish AnastasiiaPortfolio.csproj -c Release -o publish"

[deploy]
startCommand = "dotnet publish/AnastasiiaPortfolio.dll"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:5000" 